#!/bin/sh

##############################################################################
##  Gradle start up script for POSIX generated by Gradle.
##############################################################################

APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD=$( find /Applications/Android\ Studio.app/Contents/jbr/Contents/Home/bin -name java 2>/dev/null | head -1 )
    if [ -z "$JAVACMD" ]; then
        JAVACMD="java"
    fi
fi

exec "$JAVACMD" \
    -Xmx64m -Xms64m \
    $JAVA_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
